services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: workly-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: workly
      POSTGRES_USER: workly
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - workly-network

  # Redis (Socket.io Adapter용)
  redis:
    image: redis:7-alpine
    container_name: workly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workly-network

  # Backend (NestJS)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: workly-backend
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=workly
      - DATABASE_USERNAME=workly
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - workly-network
    restart: unless-stopped

  # Frontend (Next.js)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: workly-frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - workly-network
    restart: unless-stopped

  # MinIO (S3 호환 로컬 스토리지 - 개발용)
  minio:
    image: minio/minio:latest
    container_name: workly-minio
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - workly-network
    command: server /data --console-address ":9001"

  # Nginx (리버스 프록시)
  nginx:
    image: nginx:alpine
    container_name: workly-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
    depends_on:
      - frontend
      - backend
    networks:
      - workly-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  workly-network:
    driver: bridge