// 어드민 컴포넌트 통합 내보내기
export { default as PermissionGuard, usePermissions } from './PermissionGuard';
export { 
  default as AdminButton,
  DeleteUserButton,
  EditUserButton,
  DeleteProjectButton,
} from './AdminButton';
export { 
  default as AdminNavItem,
  AdminNavGroup,
} from './AdminNavItem';

// 권한 상수들
export const ADMIN_PERMISSIONS = {
  // 사용자 관리
  USERS_READ: 'admin:users:read',
  USERS_CREATE: 'admin:users:create',
  USERS_UPDATE: 'admin:users:update',
  USERS_DELETE: 'admin:users:delete',
  
  // 역할 관리
  ROLES_MANAGE: 'admin:roles:manage',
  
  // 프로젝트 관리
  PROJECTS_READ: 'admin:projects:read',
  PROJECTS_CREATE: 'admin:projects:create',
  PROJECTS_UPDATE: 'admin:projects:update',
  PROJECTS_DELETE: 'admin:projects:delete',
  
  // 업무 관리
  TASKS_READ: 'admin:tasks:read',
  TASKS_CREATE: 'admin:tasks:create',
  TASKS_UPDATE: 'admin:tasks:update',
  TASKS_DELETE: 'admin:tasks:delete',
  
  // 시스템 설정
  SETTINGS_READ: 'admin:settings:read',
  SETTINGS_UPDATE: 'admin:settings:update',
  
  // 감사 로그
  AUDIT_READ: 'admin:audit:read',
  
  // 대시보드
  DASHBOARD_READ: 'admin:dashboard:read',
  
  // 프로필 관리
  PROFILE_READ: 'admin:profile:read',
  PROFILE_UPDATE: 'admin:profile:update',
} as const;

// 역할별 기본 권한 그룹 (읽기 전용)
export const ROLE_PERMISSION_GROUPS = {
  SUPER_ADMIN: Object.values(ADMIN_PERMISSIONS),
  
  ADMIN: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.USERS_CREATE,
    ADMIN_PERMISSIONS.USERS_UPDATE,
    ADMIN_PERMISSIONS.PROJECTS_READ,
    ADMIN_PERMISSIONS.PROJECTS_CREATE,
    ADMIN_PERMISSIONS.PROJECTS_UPDATE,
    ADMIN_PERMISSIONS.PROJECTS_DELETE,
    ADMIN_PERMISSIONS.TASKS_READ,
    ADMIN_PERMISSIONS.TASKS_CREATE,
    ADMIN_PERMISSIONS.TASKS_UPDATE,
    ADMIN_PERMISSIONS.TASKS_DELETE,
    ADMIN_PERMISSIONS.SETTINGS_READ,
    ADMIN_PERMISSIONS.AUDIT_READ,
    ADMIN_PERMISSIONS.DASHBOARD_READ,
    ADMIN_PERMISSIONS.PROFILE_READ,
    ADMIN_PERMISSIONS.PROFILE_UPDATE,
  ],
  
  MODERATOR: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.USERS_UPDATE,
    ADMIN_PERMISSIONS.PROJECTS_READ,
    ADMIN_PERMISSIONS.PROJECTS_UPDATE,
    ADMIN_PERMISSIONS.TASKS_READ,
    ADMIN_PERMISSIONS.TASKS_UPDATE,
    ADMIN_PERMISSIONS.DASHBOARD_READ,
    ADMIN_PERMISSIONS.PROFILE_READ,
    ADMIN_PERMISSIONS.PROFILE_UPDATE,
  ],
  
  SUPPORT: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.PROJECTS_READ,
    ADMIN_PERMISSIONS.TASKS_READ,
    ADMIN_PERMISSIONS.DASHBOARD_READ,
    ADMIN_PERMISSIONS.PROFILE_READ,
  ],
} as const;

// 권한 그룹 유틸리티
export const PERMISSION_GROUPS = {
  USER_MANAGEMENT: [
    ADMIN_PERMISSIONS.USERS_READ,
    ADMIN_PERMISSIONS.USERS_CREATE,
    ADMIN_PERMISSIONS.USERS_UPDATE,
    ADMIN_PERMISSIONS.USERS_DELETE,
    ADMIN_PERMISSIONS.ROLES_MANAGE,
  ],
  
  PROJECT_MANAGEMENT: [
    ADMIN_PERMISSIONS.PROJECTS_READ,
    ADMIN_PERMISSIONS.PROJECTS_CREATE,
    ADMIN_PERMISSIONS.PROJECTS_UPDATE,
    ADMIN_PERMISSIONS.PROJECTS_DELETE,
  ],
  
  TASK_MANAGEMENT: [
    ADMIN_PERMISSIONS.TASKS_READ,
    ADMIN_PERMISSIONS.TASKS_CREATE,
    ADMIN_PERMISSIONS.TASKS_UPDATE,
    ADMIN_PERMISSIONS.TASKS_DELETE,
  ],
  
  SYSTEM_ADMINISTRATION: [
    ADMIN_PERMISSIONS.SETTINGS_READ,
    ADMIN_PERMISSIONS.SETTINGS_UPDATE,
    ADMIN_PERMISSIONS.AUDIT_READ,
  ],
  
  BASIC_ACCESS: [
    ADMIN_PERMISSIONS.DASHBOARD_READ,
    ADMIN_PERMISSIONS.PROFILE_READ,
    ADMIN_PERMISSIONS.PROFILE_UPDATE,
  ],
} as const;